version: "3"
services:
  #### 
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
  ####
  prometheus:
    build: ./monitor
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitor/:/etc/prometheus/
    ports:
      - 9090:9090
  ####
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./monitor/grafana:/var/lib/grafana
    ports:
      - 3000:3000
